server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    name: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
  cloud:
    zookeeper:
      connect-string: localhost:2181

  