server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    name: postgres
    password: mny10602
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    zookeeper:
      connect-string: localhost:2181

  